//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldpayAddressValidationServiceClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPackets", Namespace="http://Paymetric/XiPaySoap30/message/")]
    public partial class IPackets : object
    {
        
        private int countField;
        
        private bool xipayvbresultField;
        
        private WorldpayAddressValidationServiceClient.ITransactionHeader[] packetsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool xipayvbresult
        {
            get
            {
                return this.xipayvbresultField;
            }
            set
            {
                this.xipayvbresultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WorldpayAddressValidationServiceClient.ITransactionHeader[] packets
        {
            get
            {
                return this.packetsField;
            }
            set
            {
                this.packetsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ITransactionHeader", Namespace="http://Paymetric/XiPaySoap30/message/")]
    public partial class ITransactionHeader : object
    {
        
        private string AVSAddressField;
        
        private string AVSCodeField;
        
        private string AVSZipCodeField;
        
        private string AccountingDocNumberField;
        
        private string ActionCodeField;
        
        private string AdditionalInfoField;
        
        private string AmountField;
        
        private string AuthorizationCodeField;
        
        private System.DateTime AuthorizationDateField;
        
        private string AuthorizationReferenceCodeField;
        
        private string AuthorizationTimeField;
        
        private string AuthorizedThroughCartridgeField;
        
        private string BankBatchIDField;
        
        private string BankSubBatchIDField;
        
        private string BankTransactionIDField;
        
        private string BatchIDField;
        
        private System.DateTime BillingDateField;
        
        private string BillingPlanItemField;
        
        private System.DateTime CaptureDateField;
        
        private string CaptureReferenceCodeField;
        
        private string CardCVV2Field;
        
        private string CardDataSourceField;
        
        private string CardExpirationDateField;
        
        private string CardFollowOnNumberField;
        
        private string CardHolderAddress1Field;
        
        private string CardHolderAddress2Field;
        
        private string CardHolderCityField;
        
        private string CardHolderCountryField;
        
        private string CardHolderDistrictField;
        
        private string CardHolderName1Field;
        
        private string CardHolderName2Field;
        
        private string CardHolderNameField;
        
        private string CardHolderStateField;
        
        private string CardHolderZipField;
        
        private string CardNumberField;
        
        private int CardPresentField;
        
        private string CardTypeField;
        
        private string CardValidFromField;
        
        private string ChargeAmountField;
        
        private string ClientField;
        
        private string CompanyCodeField;
        
        private System.DateTime CreationDateField;
        
        private string CurrencyKeyField;
        
        private string CustTXNField;
        
        private string CustomerNumberField;
        
        private string FiscalYearField;
        
        private string GLAccountField;
        
        private System.DateTime LastModificationDateField;
        
        private string LocationIDField;
        
        private string MerchantIDField;
        
        private string MerchantTXNField;
        
        private string MerchantTransactionIDField;
        
        private string MessageField;
        
        private int ModifiedStatusField;
        
        private System.DateTime OrderDateField;
        
        private string OrderIDField;
        
        private string OriginField;
        
        private string PONumberField;
        
        private int PacketOperationField;
        
        private string PreauthorizedField;
        
        private string ReferenceCodeField;
        
        private string ReferenceLineItemField;
        
        private string ResponseCodeField;
        
        private string SalesDocNumberField;
        
        private string SettlementAmountField;
        
        private System.DateTime SettlementDateField;
        
        private string SettlementReferenceCodeField;
        
        private System.DateTime ShippingCaptureDateField;
        
        private string ShippingLocationIDField;
        
        private string ShippingMethodField;
        
        private int StatusCodeField;
        
        private string StatusTXNField;
        
        private string TaxLevel1Field;
        
        private string TaxLevel2Field;
        
        private string TaxLevel3Field;
        
        private string TaxLevel4Field;
        
        private string TerminalIDField;
        
        private string TransactionIDField;
        
        private string TransactionTypeField;
        
        private string VATNumberCustomerField;
        
        private string VATNumberMerchantField;
        
        private string XIIDField;
        
        private WorldpayAddressValidationServiceClient.InfoItem[] InfoItemsField;
        
        private WorldpayAddressValidationServiceClient.LineItem[] LineItemsField;
        
        private WorldpayAddressValidationServiceClient.InfoItem[] SourceSystemInfoItemsField;
        
        private WorldpayAddressValidationServiceClient.BlobItem[] BlobItemsField;
        
        private WorldpayAddressValidationServiceClient.CheckImage[] CheckImagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AVSAddress
        {
            get
            {
                return this.AVSAddressField;
            }
            set
            {
                this.AVSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AVSCode
        {
            get
            {
                return this.AVSCodeField;
            }
            set
            {
                this.AVSCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AVSZipCode
        {
            get
            {
                return this.AVSZipCodeField;
            }
            set
            {
                this.AVSZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountingDocNumber
        {
            get
            {
                return this.AccountingDocNumberField;
            }
            set
            {
                this.AccountingDocNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ActionCode
        {
            get
            {
                return this.ActionCodeField;
            }
            set
            {
                this.ActionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AdditionalInfo
        {
            get
            {
                return this.AdditionalInfoField;
            }
            set
            {
                this.AdditionalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuthorizationCode
        {
            get
            {
                return this.AuthorizationCodeField;
            }
            set
            {
                this.AuthorizationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime AuthorizationDate
        {
            get
            {
                return this.AuthorizationDateField;
            }
            set
            {
                this.AuthorizationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuthorizationReferenceCode
        {
            get
            {
                return this.AuthorizationReferenceCodeField;
            }
            set
            {
                this.AuthorizationReferenceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuthorizationTime
        {
            get
            {
                return this.AuthorizationTimeField;
            }
            set
            {
                this.AuthorizationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuthorizedThroughCartridge
        {
            get
            {
                return this.AuthorizedThroughCartridgeField;
            }
            set
            {
                this.AuthorizedThroughCartridgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankBatchID
        {
            get
            {
                return this.BankBatchIDField;
            }
            set
            {
                this.BankBatchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankSubBatchID
        {
            get
            {
                return this.BankSubBatchIDField;
            }
            set
            {
                this.BankSubBatchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankTransactionID
        {
            get
            {
                return this.BankTransactionIDField;
            }
            set
            {
                this.BankTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BatchID
        {
            get
            {
                return this.BatchIDField;
            }
            set
            {
                this.BatchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime BillingDate
        {
            get
            {
                return this.BillingDateField;
            }
            set
            {
                this.BillingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillingPlanItem
        {
            get
            {
                return this.BillingPlanItemField;
            }
            set
            {
                this.BillingPlanItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CaptureDate
        {
            get
            {
                return this.CaptureDateField;
            }
            set
            {
                this.CaptureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CaptureReferenceCode
        {
            get
            {
                return this.CaptureReferenceCodeField;
            }
            set
            {
                this.CaptureReferenceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardCVV2
        {
            get
            {
                return this.CardCVV2Field;
            }
            set
            {
                this.CardCVV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardDataSource
        {
            get
            {
                return this.CardDataSourceField;
            }
            set
            {
                this.CardDataSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardExpirationDate
        {
            get
            {
                return this.CardExpirationDateField;
            }
            set
            {
                this.CardExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardFollowOnNumber
        {
            get
            {
                return this.CardFollowOnNumberField;
            }
            set
            {
                this.CardFollowOnNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderAddress1
        {
            get
            {
                return this.CardHolderAddress1Field;
            }
            set
            {
                this.CardHolderAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderAddress2
        {
            get
            {
                return this.CardHolderAddress2Field;
            }
            set
            {
                this.CardHolderAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderCity
        {
            get
            {
                return this.CardHolderCityField;
            }
            set
            {
                this.CardHolderCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderCountry
        {
            get
            {
                return this.CardHolderCountryField;
            }
            set
            {
                this.CardHolderCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderDistrict
        {
            get
            {
                return this.CardHolderDistrictField;
            }
            set
            {
                this.CardHolderDistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderName1
        {
            get
            {
                return this.CardHolderName1Field;
            }
            set
            {
                this.CardHolderName1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardHolderName2
        {
            get
            {
                return this.CardHolderName2Field;
            }
            set
            {
                this.CardHolderName2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string CardHolderName
        {
            get
            {
                return this.CardHolderNameField;
            }
            set
            {
                this.CardHolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string CardHolderState
        {
            get
            {
                return this.CardHolderStateField;
            }
            set
            {
                this.CardHolderStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string CardHolderZip
        {
            get
            {
                return this.CardHolderZipField;
            }
            set
            {
                this.CardHolderZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public int CardPresent
        {
            get
            {
                return this.CardPresentField;
            }
            set
            {
                this.CardPresentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string CardType
        {
            get
            {
                return this.CardTypeField;
            }
            set
            {
                this.CardTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string CardValidFrom
        {
            get
            {
                return this.CardValidFromField;
            }
            set
            {
                this.CardValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string ChargeAmount
        {
            get
            {
                return this.ChargeAmountField;
            }
            set
            {
                this.ChargeAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=41)]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string CurrencyKey
        {
            get
            {
                return this.CurrencyKeyField;
            }
            set
            {
                this.CurrencyKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string CustTXN
        {
            get
            {
                return this.CustTXNField;
            }
            set
            {
                this.CustTXNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string FiscalYear
        {
            get
            {
                return this.FiscalYearField;
            }
            set
            {
                this.FiscalYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string GLAccount
        {
            get
            {
                return this.GLAccountField;
            }
            set
            {
                this.GLAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=47)]
        public System.DateTime LastModificationDate
        {
            get
            {
                return this.LastModificationDateField;
            }
            set
            {
                this.LastModificationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string MerchantID
        {
            get
            {
                return this.MerchantIDField;
            }
            set
            {
                this.MerchantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string MerchantTXN
        {
            get
            {
                return this.MerchantTXNField;
            }
            set
            {
                this.MerchantTXNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string MerchantTransactionID
        {
            get
            {
                return this.MerchantTransactionIDField;
            }
            set
            {
                this.MerchantTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=53)]
        public int ModifiedStatus
        {
            get
            {
                return this.ModifiedStatusField;
            }
            set
            {
                this.ModifiedStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=54)]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string Origin
        {
            get
            {
                return this.OriginField;
            }
            set
            {
                this.OriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=57)]
        public string PONumber
        {
            get
            {
                return this.PONumberField;
            }
            set
            {
                this.PONumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=58)]
        public int PacketOperation
        {
            get
            {
                return this.PacketOperationField;
            }
            set
            {
                this.PacketOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string Preauthorized
        {
            get
            {
                return this.PreauthorizedField;
            }
            set
            {
                this.PreauthorizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=60)]
        public string ReferenceCode
        {
            get
            {
                return this.ReferenceCodeField;
            }
            set
            {
                this.ReferenceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=61)]
        public string ReferenceLineItem
        {
            get
            {
                return this.ReferenceLineItemField;
            }
            set
            {
                this.ReferenceLineItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public string SalesDocNumber
        {
            get
            {
                return this.SalesDocNumberField;
            }
            set
            {
                this.SalesDocNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=64)]
        public string SettlementAmount
        {
            get
            {
                return this.SettlementAmountField;
            }
            set
            {
                this.SettlementAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=65)]
        public System.DateTime SettlementDate
        {
            get
            {
                return this.SettlementDateField;
            }
            set
            {
                this.SettlementDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=66)]
        public string SettlementReferenceCode
        {
            get
            {
                return this.SettlementReferenceCodeField;
            }
            set
            {
                this.SettlementReferenceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=67)]
        public System.DateTime ShippingCaptureDate
        {
            get
            {
                return this.ShippingCaptureDateField;
            }
            set
            {
                this.ShippingCaptureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=68)]
        public string ShippingLocationID
        {
            get
            {
                return this.ShippingLocationIDField;
            }
            set
            {
                this.ShippingLocationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=69)]
        public string ShippingMethod
        {
            get
            {
                return this.ShippingMethodField;
            }
            set
            {
                this.ShippingMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=70)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=71)]
        public string StatusTXN
        {
            get
            {
                return this.StatusTXNField;
            }
            set
            {
                this.StatusTXNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=72)]
        public string TaxLevel1
        {
            get
            {
                return this.TaxLevel1Field;
            }
            set
            {
                this.TaxLevel1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=73)]
        public string TaxLevel2
        {
            get
            {
                return this.TaxLevel2Field;
            }
            set
            {
                this.TaxLevel2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=74)]
        public string TaxLevel3
        {
            get
            {
                return this.TaxLevel3Field;
            }
            set
            {
                this.TaxLevel3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=75)]
        public string TaxLevel4
        {
            get
            {
                return this.TaxLevel4Field;
            }
            set
            {
                this.TaxLevel4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=76)]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=77)]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=78)]
        public string TransactionType
        {
            get
            {
                return this.TransactionTypeField;
            }
            set
            {
                this.TransactionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=79)]
        public string VATNumberCustomer
        {
            get
            {
                return this.VATNumberCustomerField;
            }
            set
            {
                this.VATNumberCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=80)]
        public string VATNumberMerchant
        {
            get
            {
                return this.VATNumberMerchantField;
            }
            set
            {
                this.VATNumberMerchantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=81)]
        public string XIID
        {
            get
            {
                return this.XIIDField;
            }
            set
            {
                this.XIIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=82)]
        public WorldpayAddressValidationServiceClient.InfoItem[] InfoItems
        {
            get
            {
                return this.InfoItemsField;
            }
            set
            {
                this.InfoItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=83)]
        public WorldpayAddressValidationServiceClient.LineItem[] LineItems
        {
            get
            {
                return this.LineItemsField;
            }
            set
            {
                this.LineItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=84)]
        public WorldpayAddressValidationServiceClient.InfoItem[] SourceSystemInfoItems
        {
            get
            {
                return this.SourceSystemInfoItemsField;
            }
            set
            {
                this.SourceSystemInfoItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=85)]
        public WorldpayAddressValidationServiceClient.BlobItem[] BlobItems
        {
            get
            {
                return this.BlobItemsField;
            }
            set
            {
                this.BlobItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=86)]
        public WorldpayAddressValidationServiceClient.CheckImage[] CheckImages
        {
            get
            {
                return this.CheckImagesField;
            }
            set
            {
                this.CheckImagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoItem", Namespace="http://Paymetric/XiPaySoap30/message/")]
    public partial class InfoItem : object
    {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineItem", Namespace="http://Paymetric/XiPaySoap30/message/")]
    public partial class LineItem : object
    {
        
        private string UPCField;
        
        private string MaterialNumberField;
        
        private string DescriptionField;
        
        private string SalesDocItemNumberField;
        
        private string ActualInvoicedQuantityField;
        
        private string SalesUnitField;
        
        private string TaxAmountField;
        
        private string NetValueField;
        
        private WorldpayAddressValidationServiceClient.InfoItem[] InfoItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UPC
        {
            get
            {
                return this.UPCField;
            }
            set
            {
                this.UPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MaterialNumber
        {
            get
            {
                return this.MaterialNumberField;
            }
            set
            {
                this.MaterialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SalesDocItemNumber
        {
            get
            {
                return this.SalesDocItemNumberField;
            }
            set
            {
                this.SalesDocItemNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ActualInvoicedQuantity
        {
            get
            {
                return this.ActualInvoicedQuantityField;
            }
            set
            {
                this.ActualInvoicedQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SalesUnit
        {
            get
            {
                return this.SalesUnitField;
            }
            set
            {
                this.SalesUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NetValue
        {
            get
            {
                return this.NetValueField;
            }
            set
            {
                this.NetValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public WorldpayAddressValidationServiceClient.InfoItem[] InfoItems
        {
            get
            {
                return this.InfoItemsField;
            }
            set
            {
                this.InfoItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobItem", Namespace="http://Paymetric/XiPaySoap30/message/")]
    public partial class BlobItem : object
    {
        
        private string BlobXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BlobXML
        {
            get
            {
                return this.BlobXMLField;
            }
            set
            {
                this.BlobXMLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckImage", Namespace="http://Paymetric/XiPaySoap30/message/")]
    public partial class CheckImage : object
    {
        
        private string DescriptionField;
        
        private string FormatField;
        
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Format
        {
            get
            {
                return this.FormatField;
            }
            set
            {
                this.FormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Paymetric/XiPaySoap30", ConfigurationName="WorldpayAddressValidationServiceClient.XiPayWSSoap")]
    public interface XiPayWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="Paymetric/XiPaySoap30/action/XiGGE.SoapOp", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldpayAddressValidationServiceClient.SoapOpResponse> SoapOpAsync(WorldpayAddressValidationServiceClient.SoapOpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoapOp", WrapperNamespace="http://Paymetric/XiPaySoap30/message/", IsWrapped=true)]
    public partial class SoapOpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Paymetric/XiPaySoap30/message/", Order=0)]
        public WorldpayAddressValidationServiceClient.IPackets pPacketsIn;
        
        public SoapOpRequest()
        {
        }
        
        public SoapOpRequest(WorldpayAddressValidationServiceClient.IPackets pPacketsIn)
        {
            this.pPacketsIn = pPacketsIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SoapOpResponse", WrapperNamespace="http://Paymetric/XiPaySoap30/message/", IsWrapped=true)]
    public partial class SoapOpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Paymetric/XiPaySoap30/message/", Order=0)]
        public WorldpayAddressValidationServiceClient.IPackets SoapOpResult;
        
        public SoapOpResponse()
        {
        }
        
        public SoapOpResponse(WorldpayAddressValidationServiceClient.IPackets SoapOpResult)
        {
            this.SoapOpResult = SoapOpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface XiPayWSSoapChannel : WorldpayAddressValidationServiceClient.XiPayWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class XiPayWSSoapClient : System.ServiceModel.ClientBase<WorldpayAddressValidationServiceClient.XiPayWSSoap>, WorldpayAddressValidationServiceClient.XiPayWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XiPayWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(XiPayWSSoapClient.GetBindingForEndpoint(endpointConfiguration), XiPayWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XiPayWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XiPayWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XiPayWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XiPayWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XiPayWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldpayAddressValidationServiceClient.SoapOpResponse> WorldpayAddressValidationServiceClient.XiPayWSSoap.SoapOpAsync(WorldpayAddressValidationServiceClient.SoapOpRequest request)
        {
            return base.Channel.SoapOpAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldpayAddressValidationServiceClient.SoapOpResponse> SoapOpAsync(WorldpayAddressValidationServiceClient.IPackets pPacketsIn)
        {
            WorldpayAddressValidationServiceClient.SoapOpRequest inValue = new WorldpayAddressValidationServiceClient.SoapOpRequest();
            inValue.pPacketsIn = pPacketsIn;
            return ((WorldpayAddressValidationServiceClient.XiPayWSSoap)(this)).SoapOpAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XiPayWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.XiPayWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XiPayWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cert-xipayapi.paymetric.com/PMXIGGE/XiPay30WS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.XiPayWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cert-xipayapi.paymetric.com/PMXIGGE/XiPay30WS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            XiPayWSSoap,
            
            XiPayWSSoap12,
        }
    }
}
